[phases.build]
# Comandos para dar permissão ao script gradlew e construir a aplicação
cmds = [
  "chmod +x backend-kotlin/gradlew",   # Dá permissão ao script gradlew
  "cd backend-kotlin && ./gradlew build"  # Navega até o diretório backend-kotlin e executa o build
]

[start]
# Comando para iniciar a aplicação a partir do binário gerado pelo Gradle
cmd = "./backend-kotlin/build/install/backend-kotlin/bin/backend-kotlin"
