# Fase de build: como construir a aplicação
[phases.build]
# Comandos a serem executados:
# 1. Dá permissão de execução ao script do Gradle (solução para o erro comum)
# 2. Navega para a pasta do backend e executa o comando de build
cmds = ["chmod +x backend-kotlin/gradlew", "cd backend-kotlin && ./gradlew build"]

# Fase de start: como iniciar a aplicação depois de construída
[start]
# Comando para executar a aplicação a partir da raiz do repositório
cmd = "./backend-kotlin/build/install/backend-kotlin/bin/backend-kotlin"


