# Fase de build: como construir a aplicação
[phases.build]
# Comandos a serem executados para construir a aplicação
cmds = [
  "gradle build"  # Usa o Gradle instalado globalmente para construir o projeto
]

# Fase de start: como iniciar a aplicação depois de construída
[start]
# Comando para executar a aplicação após a construção
cmd = "java -jar build/libs/backend-kotlin-0.0.1.jar"


